### ISSUE TITLE
Username Password

### ISSUE THREAD

**Issue by Schokgolf** [edinsoncs/Sistema-Restaurante#2]
what are the default username and password? can't locate these in the project

**Comment by edinsoncs** [comment]
hi, you have to insert in the bd the user and password to enter

**Comment by Blooopa** [comment]
Hi
how is the structure of the document on DB?/Como es la estructura del documento en la BD?

**Comment by Blooopa** [comment]
Podrias guiarme para un configurarion incial y básica, levante el proyecto pero llegue hasta ahi. Gracias.

**Comment by edinsoncs** [comment]
Hola el modelo es simple, solo tienes que crear un usuario y contraseña, slds

**Comment by ugintl** [comment]
@Blooopa Can you tell me how I can install this app? WHat tools I would need?
